// 30-day WSPR spot baseline lookup. Drives the one-way 'busier than
// average' override that promotes a band's tier to 'good' when current
// activity exceeds the baseline.

import SPOT_BASELINES from "../data/spot-baselines.mjs";

// Per-(band, UTC-hour) 30-day mean WSPR spot rate. The override below
// fires when right-now spots exceed this baseline -- i.e. the band is
// busier than usual for the time of day. Baseline regenerated by
// `node scripts/harness.mjs wspr-baselines`.
//
// Fallback if the JSON is missing or malformed: Infinity (override
// never fires) so we never promote on bad data.
export function spotBaselineMean(bandName, nowDate) {
  var band = SPOT_BASELINES && SPOT_BASELINES.bands && SPOT_BASELINES.bands[bandName];
  if (!band || !band.length) return Infinity;
  var hour = nowDate ? nowDate.getUTCHours() : new Date().getUTCHours();
  var v = band[hour];
  return (typeof v === "number" && v > 0) ? v : Infinity;
}
