// 30-day WSPR spot baseline lookup. Drives the one-way 'busier than
// average' override that promotes a band's tier to 'good' when current
// activity exceeds the baseline.

import SPOT_BASELINES from "../data/spot-baselines.mjs";

// Per-(band, UTC-hour) 30-day mean WSPR spot rate. The override below
// fires when right-now spots exceed this baseline -- i.e. the band is
// busier than usual for the time of day. Baseline regenerated by
// `node scripts/harness.mjs wspr-baselines`.
//
// Fallback if the JSON is missing or malformed: Infinity (override
// never fires) so we never promote on bad data.
export function spotBaselineMean(bandName, nowDate) {
  var band = SPOT_BASELINES && SPOT_BASELINES.bands && SPOT_BASELINES.bands[bandName];
  if (!band || !band.length) return Infinity;
  // Linear interpolation between adjacent hour buckets so a spot at
  // 13:59 UTC doesn't read a different baseline from one at 14:01 just
  // because the integer hour changed. Without this the override flips
  // discretely at every UTC hour boundary even though activity is
  // continuous.
  var d    = nowDate || new Date();
  var hour = d.getUTCHours();
  var frac = (d.getUTCMinutes() * 60 + d.getUTCSeconds()) / 3600;
  var lo = band[hour];
  var hi = band[(hour + 1) % band.length];
  var loOK = typeof lo === "number" && lo > 0;
  var hiOK = typeof hi === "number" && hi > 0;
  if (loOK && hiOK)  return lo + (hi - lo) * frac;
  if (loOK)          return lo;
  if (hiOK)          return hi;
  return Infinity;
}
